name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-python:
    name: "Python ${{ matrix.python-version }} Build"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7]
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          # python -m pip install -r tests/requirements.txt
          python -m pip install yapf==0.31 flake8

      - name: Check Python formatting
        run: |
          yapf --diff --recursive ./python-libraries/
          flake8 ./python-libraries/
          yapf --diff --recursive ./tests/
          flake8 ./tests/
          yapf --diff scripts/run_offline_pipeline.py
          flake8 scripts/run_offline_pipeline.py
          yapf --diff scripts/get_argo_2d_bboxes.py 

      # - name: Run tests
      #   run: |
      #     python -m pytest tests/
